# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 22:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timetable', '0002_consultation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='consultation',
            unique_together=set([('date', 'doctor', 'client')]),
        ),
    ]
