# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 22:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_auto_20170831_2250'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='consultation',
            unique_together=set([('date', 'doctor')]),
        ),
    ]
